In [ ]:
import pandas as pd
import numpy as np
from datetime import date
import matplotlib.pyplot as plt

In [ ]:
df1=pd.read_csv("./data/raw/listings.csv")
df2=pd.read_csv("./data/raw/neighbourhoods.csv")

In [ ]:
df1.isna().sum()*100/len(df1)

listing_id            0.000000
city                  0.000000
neighbourhood         0.000000
property_type         0.000000
bedrooms              0.000000
bathrooms             0.000000
area_sqm              0.000000
building_age_years    0.000000
floor                 0.000000
has_generator         0.000000
has_borehole          0.000000
tiled                 0.000000
gated_security        0.000000
furnished             0.000000
listed_on             0.000000
listing_source        0.000000
monthly_rent_xaf      7.807571
dtype: float64

In [14]:
df1.info

<bound method DataFrame.info of      listing_id     city neighbourhood    property_type  bedrooms  bathrooms  \
0      LS-00164  Yaounde          Golf  chambre moderne         2          3
1      LS-02883   Douala          Akwa        apartment         1          2
2      LS-03740   Douala          Akwa            villa         3          3
3      LS-03477   Douala       Ndokoti           studio         4          3
4      LS-00633   Douala       Ndokoti        apartment         2          2
...         ...      ...           ...              ...       ...        ...
6335   LS-02163   Douala      New Bell            villa         2          2
6336   LS-04531  Yaounde         Emana        apartment         1          1
6337   LS-05459  Yaounde       Mendong        apartment         2          2
6338   LS-01922  Yaounde        Bastos           duplex         3          3
6339   LS-00512  Yaounde        Etoudi            villa         3          3

     area_sqm  building_age_years  floor has_generator  has_borehole  tiled  \
0        63.8                   0      1         FALSE          True   True
1        42.8                   0      3         FALSE         False   True
2        77.3                  13      4          TRUE          True  False
3       360.3                  19      1         FALSE         False   True
4        58.9                  14      1         FALSE         False  False
...       ...                 ...    ...           ...           ...    ...
6335     95.9                  17      4         FALSE          True  False
6336     49.0                   0      1         FALSE         False   True
6337     66.2                   6      0          TRUE         False   True
6338     99.7                   0      2         FALSE          True  False
6339     88.6                   0      4         FALSE         False  False

      gated_security  furnished   listed_on listing_source monthly_rent_xaf
0               True      False  2026-04-26       informal           219794
1               True      False  2025-09-18         portal           222273
2              False      False  2025-12-17         agency           196239
3              False      False  2026-06-02       informal              NaN
4              False      False  04/07/2026         portal           101872
...              ...        ...         ...            ...              ...
6335           False       True  26/12/2025         portal           211516
6336            True      False  2025-08-03         portal           170221
6337           False      False  2025-07-20       informal            79721
6338           False       True  2025-11-30         agency           422579
6339           False      False  13/07/2026       informal              NaN

[6340 rows x 17 columns]>

In [15]:
df1.head(19)

,listing_id,city,neighbourhood,property_type,bedrooms,bathrooms,area_sqm,building_age_years,floor,has_generator,has_borehole,tiled,gated_security,furnished,listed_on,listing_source,monthly_rent_xaf
0,LS-00164,Yaounde,Golf,chambre moderne,2,3,63.8,0,1,FALSE,True,True,True,False,2026-04-26,informal,219794
1,LS-02883,Douala,Akwa,apartment,1,2,42.8,0,3,FALSE,False,True,True,False,2025-09-18,portal,222273
2,LS-03740,Douala,Akwa,villa,3,3,77.3,13,4,TRUE,True,False,False,False,2025-12-17,agency,196239
3,LS-03477,Douala,Ndokoti,studio,4,3,360.3,19,1,FALSE,False,True,False,False,2026-06-02,informal,NaN
4,LS-00633,Douala,Ndokoti,apartment,2,2,58.9,14,1,FALSE,False,False,False,False,04/07/2026,portal,101872
5,LS-02512,Yaounde,Bastos,apartment,1,1,67.1,1,3,TRUE,False,False,False,False,2025-08-14,portal,264249
6,LS-05639,Yaounde,Etoudi,duplex,1,2,21.9,6,2,FALSE,False,True,True,False,2025-12-18,informal,87973
7,LS-06085,Douala,Bonanjo,apartment,3,3,108.1,2,1,TRUE,False,True,False,False,2025-08-08,informal,NaN
8,LS-04351,Yaounde,Nkolbisson,villa,1,1,57.4,24,0,FALSE,False,False,False,False,2025-08-13,agency,71871
9,LS-04330,Douala,Deido,villa,2,2,87.0,18,1,FALSE,False,False,False,False,2026-08-06,agency,248571
10,LS-04606,Yaounde,Golf,villa,1,2,44.9,0,1,TRUE,True,False,False,False,15/12/2025,agency,193953
11,LS-03253,Yaounde,Bastos,apartment,2,2,69.4,27,4,TRUE,False,True,True,False,2026-02-22,agency,230271
12,LS-01660,Yaounde,Bastos,duplex,1,1,32.0,8,1,FALSE,True,True,True,False,2025-08-04,portal,177050
13,LS-00871,Yaounde,Nsam,chambre moderne,2,2,74.6,6,1,TRUE,False,False,False,False,2025-10-01,informal,214038
14,LS-01394,Douala,Ndokoti,apartment,1,2,44.4,9,3,FALSE,False,True,False,False,2026-08-24,agency,97484
15,LS-01483,Douala,New Bell,apartment,1,1,36.9,13,2,FALSE,True,False,False,False,09/12/2025,informal,69614
16,LS-03779,Douala,Bonamoussadi,chambre moderne,2,2,72.2,7,0,FALSE,False,False,False,False,23/05/2026,portal,318766
17,LS-04596,Douala,Makepe,chambre moderne,2,1,74.6,16,3,FALSE,False,True,False,True,2025-08-14,portal,161774
18,LS-00022,Douala,Bonamoussadi,apartment,1,1,54.7,4,1,FALSE,False,False,True,False,2025-12-09,agency,114213

In [24]:
df1=df1.dropna()

In [25]:
df1.isnull().sum()*100/len(df1)

listing_id            0.0
city                  0.0
neighbourhood         0.0
property_type         0.0
bedrooms              0.0
bathrooms             0.0
area_sqm              0.0
building_age_years    0.0
floor                 0.0
has_generator         0.0
has_borehole          0.0
tiled                 0.0
gated_security        0.0
furnished             0.0
listed_on             0.0
listing_source        0.0
monthly_rent_xaf      0.0
dtype: float64

In [47]:
df1["listed_on"].unique()

<ArrowStringArray>
['2026-04-26', '2025-09-18', '2025-12-17', '04/07/2026', '2025-08-14',
 '2025-12-18', '2025-08-13', '2026-08-06', '15/12/2025', '2026-02-22',
 ...
 '20/04/2026', '09/11/2025', '25/08/2025', '12/06/2026', '01/08/2025',
 '20/12/2025', '27/03/2026', '23/08/2025', '22/11/2025', '19/06/2026']
Length: 775, dtype: str

In [49]:


# Example date string
#date_str = "2023-10-15"

# Parse into a date object
date_obj = date.strptime("listed_on", "%Y-%m-%d")

# Convert to YY MM DD format using strftime with %04d for leading zeros
output_format = "%04d %02d %02d"

formatted_output = date_obj.strftime(output_format)

print(f"{"listed_on"} -> {formatted_output}")

ValueError: time data 'listed_on' does not match format '%Y-%m-%d'

In [45]:
df1.head(10)

,listing_id,city,neighbourhood,property_type,bedrooms,bathrooms,area_sqm,building_age_years,floor,has_generator,has_borehole,tiled,gated_security,furnished,listed_on,listing_source,monthly_rent_xaf
0,LS-00164,Yaounde,Golf,chambre moderne,2,3,63.8,0,1,FALSE,True,True,True,False,2026-04-26,informal,219794
1,LS-02883,Douala,Akwa,apartment,1,2,42.8,0,3,FALSE,False,True,True,False,2025-09-18,portal,222273
2,LS-03740,Douala,Akwa,villa,3,3,77.3,13,4,TRUE,True,False,False,False,2025-12-17,agency,196239
4,LS-00633,Douala,Ndokoti,apartment,2,2,58.9,14,1,FALSE,False,False,False,False,04/07/2026,portal,101872
5,LS-02512,Yaounde,Bastos,apartment,1,1,67.1,1,3,TRUE,False,False,False,False,2025-08-14,portal,264249
6,LS-05639,Yaounde,Etoudi,duplex,1,2,21.9,6,2,FALSE,False,True,True,False,2025-12-18,informal,87973
8,LS-04351,Yaounde,Nkolbisson,villa,1,1,57.4,24,0,FALSE,False,False,False,False,2025-08-13,agency,71871
9,LS-04330,Douala,Deido,villa,2,2,87.0,18,1,FALSE,False,False,False,False,2026-08-06,agency,248571
10,LS-04606,Yaounde,Golf,villa,1,2,44.9,0,1,TRUE,True,False,False,False,15/12/2025,agency,193953
11,LS-03253,Yaounde,Bastos,apartment,2,2,69.4,27,4,TRUE,False,True,True,False,2026-02-22,agency,230271

In [41]:
df1[df1.duplicated()]

Empty DataFrame
Columns: [listing_id, city, neighbourhood, property_type, bedrooms, bathrooms, area_sqm, building_age_years, floor, has_generator, has_borehole, tiled, gated_security, furnished, listed_on, listing_source, monthly_rent_xaf]
Index: []

In [39]:
df1=df1.drop_duplicates()

In [40]:
df1.duplicated().value_counts()

False    5714
Name: count, dtype: int64